version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/data/logs
            - MONGO_INITDB_ROOT_USERNAME=mongodb
            - MONGO_INITDB_ROOT_PASSWORD=123456
        volumes:
            - /data/docker/mongodb/data:/data/db
            - /data/docker/mongodb/logs:/data/logs
        ports:
            - 27017:27017
