version: '2'
services:
    mysql:
      image: mysql:8.0
      container_name: mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=123456
      ports:
        - 3306:3306
      volumes:
        - ./conf:/etc/mysql
        - ./logs:/var/log/mysql
        - ./data:/var/lib/mysql
