version: '2'
services:
    redis:
      image: redis:latest
      container_name: redis
      command: redis-server --requirepass 123456
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - ./data:/data
